name: CCTweakedCheck
on: [push, pull_request]
jobs:
  runCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Install CraftOS-PC
        run: |
          sudo add-apt-repository ppa:jackmacwindows/ppa
          sudo apt update
          sudo apt install craftos-pc
      - name: Run Script in CraftOS-PC
        run: |
          craftos --mount .=.
